### ISSUE TITLE
Suggestion - remove font-weight: bold on h1 and h2

### ISSUE THREAD

**Issue by jzhu01** [RaffaelWi/prj-rev-bwfs-dasmoto#2]
Seen here: https://github.com/RaffaelWi/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/styles.css#L7

Since the headings are bolded by default, there's no need to specify this here.

**Comment by RaffaelWi** [comment]
Noted Thank you
