### ISSUE TITLE
Suggestion - remove duplicating stylings for h2s

### ISSUE THREAD

**Issue by jzhu01** [RaffaelWi/prj-rev-bwfs-dasmoto#3]
Seen here: https://github.com/RaffaelWi/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/styles.css#L14-L16

Since these lines are used throughout the h2 stylings, it might make more sense to have a selector like: .section h2, and to apply this styling once there.

**Comment by RaffaelWi** [comment]
Thanks for the hint, noted for future projects
