### ISSUE TITLE
Suggestion - use a class on the spans, not IDs

### ISSUE THREAD

**Issue by jzhu01** [RaffaelWi/prj-rev-bwfs-dasmoto#4]
Seen here: https://github.com/RaffaelWi/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L24

Since IDs are meant to be unique and used only once, what you're looking to use here is a class.

**Comment by RaffaelWi** [comment]
Noted as well
