### ISSUE TITLE
Nice job setting the font-family once with the body selector!

### ISSUE THREAD

**Issue by jzhu01** [RaffaelWi/prj-rev-bwfs-dasmoto#5]
Seen here: https://github.com/RaffaelWi/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/styles.css#L1-L3

This was clean and avoided repetition. I like it!

**Comment by RaffaelWi** [comment]
Nice to hear that thanks :)
