### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [RaffaelWi/prj-rev-bwfs-dasmoto#6]
Awesome job on this project! I really liked how you chose to set the font-family once, and how you decided to use divs to organize your HTML. In terms of improvement, I recommend removing the font-weight:bold on your h1 and h2s, removing duplicates stylings in your code, and using classes instead of IDs when selecting the spans.

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the great work! ^_^

**Comment by RaffaelWi** [comment]
Thank you really much for the review. I noted all of your tips :) For the future i will do it like that. I will keep an eye on the duplicates in the css. :)
